# Generated by Django 4.1.7 on 2023-05-21 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.CharField(max_length=150, unique=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="users/thumnail"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ("-created", "-updated"),
            },
        ),
        migrations.CreateModel(
            name="CityCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Countrycode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Expatad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=150)),
                ("locationcode", models.CharField(max_length=200)),
                ("sublocationcode", models.CharField(max_length=200)),
                ("landmark", models.CharField(max_length=200)),
                ("area", models.CharField(default=100, max_length=100)),
                (
                    "areameasurement",
                    models.CharField(default="Square Feet", max_length=40),
                ),
                (
                    "contactno",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("zipcode", models.CharField(max_length=20)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("Description", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cover_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="users/cover_photos"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expads.category",
                    ),
                ),
                (
                    "citycode",
                    models.ForeignKey(
                        default="Jeddah",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expads.citycode",
                    ),
                ),
                (
                    "countrycode",
                    models.ForeignKey(
                        default="Saudi Arabia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expads.countrycode",
                    ),
                ),
            ],
            options={
                "verbose_name": "expatad",
                "verbose_name_plural": "expatads",
                "ordering": ("-created", "-updated"),
            },
        ),
        migrations.CreateModel(
            name="LocationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "locationcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locationcode",
                        to="expads.citycode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="SubLocationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "sublocationCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sublocationCode",
                        to="expads.locationcode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interested",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=150)),
                (
                    "contactno",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.CharField(max_length=150)),
                ("Description", models.CharField(max_length=500)),
                (
                    "is_fallowed",
                    models.CharField(
                        default="Yet Not Followed This Message", max_length=100
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpatImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.FileField(blank=True, null=True, upload_to="users/images"),
                ),
                (
                    "expatads",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expatads",
                        to="expads.expatad",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="expatad",
            name="purpose",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="expads.purpose"
            ),
        ),
        migrations.AddField(
            model_name="expatad",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Contactme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=150)),
                (
                    "contactno",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.CharField(max_length=150)),
                ("Description", models.CharField(max_length=500)),
                (
                    "is_fallowed",
                    models.CharField(
                        default="Yet Not Followed This Message", max_length=100
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="citycode",
            name="countrycode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countrycode",
                to="expads.countrycode",
            ),
        ),
    ]
